name             'issue_repro'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures build-cookbook'
long_description 'Installs/Configures build-cookbook'
version          '0.1.0'

depends 'hipchat'
depends 'chef_handler'
depends 'apt'
